/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppAppRouteImport } from './routes/app._app'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'
import { Route as AppAppIndexRouteImport } from './routes/app._app.index'
import { Route as AppAppTrackerRouteImport } from './routes/app._app.tracker'
import { Route as AppAppTeamsRouteImport } from './routes/app._app.teams'
import { Route as AppAppTasksRouteImport } from './routes/app._app.tasks'
import { Route as AppAppTagsRouteImport } from './routes/app._app.tags'
import { Route as AppAppReportsRouteImport } from './routes/app._app.reports'
import { Route as AppAppProjectsRouteImport } from './routes/app._app.projects'
import { Route as AppAppClientsRouteImport } from './routes/app._app.clients'
import { Route as AppAppCalendarRouteImport } from './routes/app._app.calendar'
import { Route as AppAppAiRouteImport } from './routes/app._app.ai'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app/_app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppTrackerRoute = AppAppTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppTeamsRoute = AppAppTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppTasksRoute = AppAppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppTagsRoute = AppAppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppReportsRoute = AppAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppProjectsRoute = AppAppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppClientsRoute = AppAppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppCalendarRoute = AppAppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppAiRoute = AppAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/app': typeof AppAppRouteWithChildren
  '/app/ai': typeof AppAppAiRoute
  '/app/calendar': typeof AppAppCalendarRoute
  '/app/clients': typeof AppAppClientsRoute
  '/app/projects': typeof AppAppProjectsRoute
  '/app/reports': typeof AppAppReportsRoute
  '/app/tags': typeof AppAppTagsRoute
  '/app/tasks': typeof AppAppTasksRoute
  '/app/teams': typeof AppAppTeamsRoute
  '/app/tracker': typeof AppAppTrackerRoute
  '/app/': typeof AppAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/app/ai': typeof AppAppAiRoute
  '/app/calendar': typeof AppAppCalendarRoute
  '/app/clients': typeof AppAppClientsRoute
  '/app/projects': typeof AppAppProjectsRoute
  '/app/reports': typeof AppAppReportsRoute
  '/app/tags': typeof AppAppTagsRoute
  '/app/tasks': typeof AppAppTasksRoute
  '/app/teams': typeof AppAppTeamsRoute
  '/app/tracker': typeof AppAppTrackerRoute
  '/app': typeof AppAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/app/_app': typeof AppAppRouteWithChildren
  '/app/_app/ai': typeof AppAppAiRoute
  '/app/_app/calendar': typeof AppAppCalendarRoute
  '/app/_app/clients': typeof AppAppClientsRoute
  '/app/_app/projects': typeof AppAppProjectsRoute
  '/app/_app/reports': typeof AppAppReportsRoute
  '/app/_app/tags': typeof AppAppTagsRoute
  '/app/_app/tasks': typeof AppAppTasksRoute
  '/app/_app/teams': typeof AppAppTeamsRoute
  '/app/_app/tracker': typeof AppAppTrackerRoute
  '/app/_app/': typeof AppAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/success'
    | '/accept-invitation/$invitationId'
    | '/app'
    | '/app/ai'
    | '/app/calendar'
    | '/app/clients'
    | '/app/projects'
    | '/app/reports'
    | '/app/tags'
    | '/app/tasks'
    | '/app/teams'
    | '/app/tracker'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/success'
    | '/accept-invitation/$invitationId'
    | '/app/ai'
    | '/app/calendar'
    | '/app/clients'
    | '/app/projects'
    | '/app/reports'
    | '/app/tags'
    | '/app/tasks'
    | '/app/teams'
    | '/app/tracker'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/success'
    | '/accept-invitation/$invitationId'
    | '/app/_app'
    | '/app/_app/ai'
    | '/app/_app/calendar'
    | '/app/_app/clients'
    | '/app/_app/projects'
    | '/app/_app/reports'
    | '/app/_app/tags'
    | '/app/_app/tasks'
    | '/app/_app/teams'
    | '/app/_app/tracker'
    | '/app/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SuccessRoute: typeof SuccessRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  AppAppRoute: typeof AppAppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app': {
      id: '/app/_app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app/': {
      id: '/app/_app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/tracker': {
      id: '/app/_app/tracker'
      path: '/tracker'
      fullPath: '/app/tracker'
      preLoaderRoute: typeof AppAppTrackerRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/teams': {
      id: '/app/_app/teams'
      path: '/teams'
      fullPath: '/app/teams'
      preLoaderRoute: typeof AppAppTeamsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/tasks': {
      id: '/app/_app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppAppTasksRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/tags': {
      id: '/app/_app/tags'
      path: '/tags'
      fullPath: '/app/tags'
      preLoaderRoute: typeof AppAppTagsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/reports': {
      id: '/app/_app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppAppReportsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/projects': {
      id: '/app/_app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppAppProjectsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/clients': {
      id: '/app/_app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppAppClientsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/calendar': {
      id: '/app/_app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppAppCalendarRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/ai': {
      id: '/app/_app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAppAiRouteImport
      parentRoute: typeof AppAppRoute
    }
  }
}

interface AppAppRouteChildren {
  AppAppAiRoute: typeof AppAppAiRoute
  AppAppCalendarRoute: typeof AppAppCalendarRoute
  AppAppClientsRoute: typeof AppAppClientsRoute
  AppAppProjectsRoute: typeof AppAppProjectsRoute
  AppAppReportsRoute: typeof AppAppReportsRoute
  AppAppTagsRoute: typeof AppAppTagsRoute
  AppAppTasksRoute: typeof AppAppTasksRoute
  AppAppTeamsRoute: typeof AppAppTeamsRoute
  AppAppTrackerRoute: typeof AppAppTrackerRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppAiRoute: AppAppAiRoute,
  AppAppCalendarRoute: AppAppCalendarRoute,
  AppAppClientsRoute: AppAppClientsRoute,
  AppAppProjectsRoute: AppAppProjectsRoute,
  AppAppReportsRoute: AppAppReportsRoute,
  AppAppTagsRoute: AppAppTagsRoute,
  AppAppTasksRoute: AppAppTasksRoute,
  AppAppTeamsRoute: AppAppTeamsRoute,
  AppAppTrackerRoute: AppAppTrackerRoute,
  AppAppIndexRoute: AppAppIndexRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SuccessRoute: SuccessRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  AppAppRoute: AppAppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
